### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [arun11299/cpp-subprocess#1]
I would like to point out that an identifier like "[`__SUBPROCESS_HPP_`](https://github.com/arun11299/cpp-subprocess/blob/5e1a9c90889febb3e95ddd572c6367ccff133ae5/subprocess.hpp#L34)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by arun11299** [comment]
Thanks @elfring . I have changed it as per the standards.

**Comment by elfring** [comment]
Thanks for [your improvement of an affected include guard](https://github.com/arun11299/cpp-subprocess/commit/a67cb2a439b21c3f03a1f9e693116b3041640bbd "Deletion of a few underscores").
