### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by jsho000** [arun11299/cpp-subprocess#103]
In the following code:

```
      int read_bytes = util::read_atmost_n(
                                  fdopen(err_rd_pipe, "r"),
                                  err_buf,
                                  SP_MAX_ERR_BUF_SIZ);
      close(err_rd_pipe);
```

The value returned by fdopen() is not closed. This causes memory leak.
If you call fclose(), it will close err_rd_pipe. So close(err_rd_pipe) is not necessary.

**Comment by arun11299** [comment]
@jsho000 Thank you for reporting. Can you provide a PR after testing the required changes ?

**Comment by arun11299** [comment]
Will be fixed with https://github.com/arun11299/cpp-subprocess/issues/104
