### ISSUE TITLE
Simple stderr example

### ISSUE THREAD

**Issue by fxfactorial** [arun11299/cpp-subprocess#15]
Hi, 

I'm looking for a way to collect only stderr from a subprocess, can you provide such an example please?

**Comment by arun11299** [comment]
Hello @fxfactorial 
From the current example:
```
auto p = Popen({"grep", "f"}, output{PIPE}, input{PIPE});
  const char* msg = "one\ntwo\nthree\nfour\nfive\n";
  p.send(msg, strlen(msg));
  auto res = p.communicate(nullptr, 0);
  std::cout << res.first.buf.data() << std::endl;
```
`res.second.buf` is basically the error data. Does this information help you with your case ?
