### ISSUE TITLE
a bug in util::read_all() function

### ISSUE THREAD

**Issue by mohamedAlaaK** [arun11299/cpp-subprocess#24]
#23 
there was a bug in util::read_all() function where it returned invalid data
`template <typename Buffer>
  static inline int read_all(int fd, Buffer& buf)`
and i don't know why the function is templated as it's dealing with a `vector<char>` and it's always called with a `vector<char>` correct me if i am wrong but anyways i changed it :D.
and we need an api of getting stdout content from a subprocess like what the test case is doing.

**Comment by arun11299** [comment]
Merged the pull request. Thanks!
