### ISSUE TITLE
string comparison issue on win32

### ISSUE THREAD

**Issue by wolfv** [arun11299/cpp-subprocess#55]
There is a char* == "w" here:

https://github.com/arun11299/cpp-subprocess/blob/f1a698b50e53e34db17e730c259cb60f023ccff2/subprocess.hpp#L239-L244

which never seems to succeed. Instead, using `strcmp(mode, "w") == 0` works as expected.

**Comment by arun11299** [comment]
@wolfv Thanks for reporting. Would you like to provide a pull request for it ?
