### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by jussihi** [arun11299/cpp-subprocess#57]
Hello,

When running multiple subprocess-instances in different threads simultaneously, the program sometimes crashes into "bad file descriptor" when writing into the subprocess pipe.

I will try to add manual thread safety to my program (so that only one thread can use `subprocess` at a time), just to be sure that this is indeed the cause of the problem. But should the library be thread-safe?

**Comment by arun11299** [comment]
Hello @jussihi 
For simplicity reasons, the library is not thread safe. It would be better to handle it in your application.

**Comment by jussihi** [comment]
@arun11299 thanks for clarifying it. I will do so in my own application.
